language: python
# https://docs.travis-ci.com/user/customizing-the-build/

# Can add more versions here if we want to test on multiple pythons
python:
  - "3.4"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# all test files must be of form test*.py
script:
  - python3 -m unittest discover --start-directory test

after_success:
  - coveralls

notifications:
    slack: carlcs-analytics:INZrta4dRGcjcdLsM6ba4L7h

services:
  - postgresql