language: python
python:
- '3.4'
install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install coveralls
script:
- python3 -m unittest discover --start-directory test
after_success:
- coveralls
- eval "$(ssh-agent -s)"
- chmod 600 travis/deploy_rsa
- ssh-add travis/deploy_rsa
- ssh michelsd@energycomps.its.carleton.edu <<EOF # Ideally we'd redo this with a user who is not dustin
  cd /var/www/html/energy-analytics-comps
  git pull # Change to whatever commands you need!
EOF
notifications:
  slack: carlcs-analytics:INZrta4dRGcjcdLsM6ba4L7h
before_install:
- openssl aes-256-cbc -K $encrypted_26d5205ad747_key -iv $encrypted_26d5205ad747_iv
  -in travis/deploy_rsa.enc -out travis/deploy_rsa -d
