language: python
# https://docs.travis-ci.com/user/customizing-the-build/

# Can add more versions here if we want to test on multiple pythons
python:
  - "3.4"

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

# all test files must be of form test*.py
script:
  - python3 -m unittest discover --start-directory test

after_success:
  - coveralls
