language: python
# https://docs.travis-ci.com/user/getting-started/
# Travis only runs builds on the commits you push after you’ve enabled the repository in Travis CI.
# https://docs.travis-ci.com/user/customizing-the-build/

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

script:
  - coverage run --source=test -m nose2.__main__ -v

after_success:
  - coveralls